name: Hello World
run-name: ${{  github.actor }} is testing out Github Actions
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  hello-job:
    runs-on: ubuntu-latest 

    steps:
      - name: echo tset
        run: echo "hello world!"

  clone:
    runs-on: ubuntu-latest
    needs: hello-job
    
    steps:
      - name: checkout
        uses: Actions/checkout@v4

        



