name: Test Hello World
run-name: ${{  github.actor }} is testing out Github Actions
on:
  workflow_dispatch:
  pull_request:   
  push:
    branches:
      - main
jobs:
  hello-job:
    runs-on: ubuntu-latest 

    steps:
      - name: echo Test
        run: echo "Test hello world!"

  clone:
    runs-on: ubuntu-latest
    needs: hello-job
    
    steps:
      - name: checkout
        uses: Actions/checkout@v4

        



